### ISSUE TITLE
Game not closing properly and will freeze unless force closed

### ISSUE THREAD

**Issue by RealSavageJef** [ScoreSpy/Issues#13]

**Comment by Ahriana** [comment]
this seams to be resolved in 1.0.9, will re-open if pointed otherwise

**Comment by Ahriana** [comment]
Hello darkness, my old friend
I've come to talk with you again

**Comment by Ahriana** [comment]
if anyone can find a reliable way to reproduce this please let me know.

**Comment by silverface1** [comment]
Hi, this is happening every time I open Scorespy, whether I play for hours or open and close right out. Sometimes, though, the window will go transparent and it _appears_ as if I am on my desktop again. Hovering over the hat icon on the taskbar on my second monitor shows a grey screen. I cannot find a way to screenshot any of this behavior, because it would just show you my desktop. However, I can provide a screen recording, linked below. My options for closing the game are ending the Clone Hero process in Task Manager, and/or closing out of the launcher itself.

System specs if it helps any: Windows 10, build 19044, AMD Ryzen 3 3200G, NVIDIA GT 1030, 16gb ram. Usually running Rainmeter and Core Temp in the background, but closing them out does nothing.

[VIDEO LINK for visualizing the bug (mic is very quiet im sorry)](https://www.youtube.com/watch?v=QvXE8RDQSq8)

**Comment by MatharuG** [comment]
> if anyone can find a reliable way to reproduce this please let me know.

Hey Ahri. My game is constantly doing that. There's no "condition" to it on my end, or a way to reproduce it. As in, **every single** time I close ScoreSpy, it crashes. Could it be system/specs related? Like, (for example) everyone with an AMD CPU gets the crash everytime, but everyone with an Intel CPU gets the crash _sometimes_.

**Comment by Ahriana** [comment]
this should be resolved
