### ISSUE TITLE
Sorting leaderboards by factors other than score

### ISSUE THREAD

**Issue by TakaDoesStuff** [ScoreSpy/Issues#66]
**What feature would you like to have added or changed?**
The ability to sort by Accuracy, Miss, SP, Max Combo, Speed, Date Played and Ghosts, both ascending and descending by simply clicking the column in the header of the leaderboard table, just like wikipedia or many other online tables.

**Is your feature request related to a problem? If so please describe the problem.**
No

**Additional context**
For example, this would be a way to see the most recent submission or see the fastest a chart has been passed

**Comment by Ahriana** [comment]
this will be something for the new site, so going to close this for now, feel free to reopen once the site is made if this feature is still lacking

**Comment by matrefeytontias** [comment]
Cross-posting here from the Discord since it is relevant to this (future) issue.

------------------------------------

In view of the recent discussion of inclusion or non-inclusion of certain stats in the score calculation, I come with a suggestion that should hopefully meet the standards of play of most people

Similar to the Filters button on a per-leaderboard basis, is a Sort option. The default value would be the current way of calculating score, which for reference includes solo bonus and SP bonus. Other metrics could be "weighted ghost inputs", "accuracy only (no SP + no solo)", "perfect play (ghosts + strummed hopos/taps)", really anything you can think of that utilizes all the stats at your disposal. This could either be selected as a drop-down list with the individual options or much like the Filters dialog works, with checkboxes representing every stat to or not to take into account. Off the top of my head, those boxes could be :
- normal notes
- sustain points
- multiplier bonus
- star power
- solo bonus
- ghost inputs weighting – using some formula or another. Prior discussion includes base_score * (1 - ghosts/notes), base_score - ghosts * 100, but more can be imagined
- strummed hopos/taps weighting – similar to the above
- and possibly more

That way people can look at exactly the leaderboard they care about.

**Comment by Ahriana** [comment]
as i keep saying, this is not something we are doing, please dont post on a closed ticket

**Comment by matrefeytontias** [comment]
> this will be something for the new site, so going to close this for now, feel free to reopen once the site is made if this feature is still lacking

I'm posting this here so that if and when you do reopen the ticket as you've said, it'll be here for further reference on the issue Taka addresses in the original post.
